#!/usr/bin/env bash
# reasoning-core — one-command install.
#
# Run this from the repo you want to gate. The script auto-detects
# $RC_REPO from its own location and writes per-repo config for every
# supported AI coding CLI (Claude Code, Gemini CLI, GitHub Copilot CLI,
# Mistral Vibe CLI) plus a direnv `.envrc`.
#
# Idempotent: files that already exist are skipped (the script will tell
# you which ones). A manifest of created paths is APPENDED to
# `.reasoning-core/install.manifest` so re-runs accumulate state and
# `uninstall.sh` knows what to remove.
#
# Defaults are conservative (shadow mode ON, fail-open). Promote later by
# editing `.envrc.local` per `docs/USAGE.md`.

set -euo pipefail

RC_REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TARGET_REPO="$(pwd)"
MANIFEST_DIR=".reasoning-core"
MANIFEST="$MANIFEST_DIR/install.manifest"

# Venv interpreter inside the reasoning-core checkout. The hooks import
# tree_sitter, transformers, fastapi, PyYAML, etc. — bare `python3` from
# system PATH almost never has those. Using the venv path is load-bearing.
RC_PYTHON="$RC_REPO/.venv/bin/python"

ok()    { printf '  \033[32m✓\033[0m %s\n' "$*"; }
skip()  { printf '  \033[33m·\033[0m %s\n' "$*"; }
warn()  { printf '  \033[33m!\033[0m %s\n' "$*" >&2; }
fail()  { printf '  \033[31m✗\033[0m %s\n' "$*" >&2; }

if [[ ! -d "$RC_REPO/src/hooks" ]]; then
  fail "RC_REPO=$RC_REPO is not a valid reasoning-core checkout (no src/hooks/)"
  exit 2
fi

if [[ ! -d .git ]] && [[ ! -f .git ]]; then
  warn "$TARGET_REPO is not a git repo. Continuing anyway."
fi

mkdir -p "$MANIFEST_DIR"
# Append, don't truncate: a re-run after a partial install must still be
# able to clean up paths recorded on a previous run.
touch "$MANIFEST"

# record <path> — append exactly once.
record() {
  local p="$1"
  if ! grep -qxF "$p" "$MANIFEST" 2>/dev/null; then
    printf '%s\n' "$p" >> "$MANIFEST"
  fi
}

# render_template <template> <target> — substitute <RC_REPO> AND replace
# the bare `python3` interpreter at the start of hook commands with the
# venv interpreter. Uses Python (not sed) so paths containing `&`, `\`, or
# `|` don't corrupt the output.
render_template() {
  local src="$1" dst="$2"
  RC_REPO="$RC_REPO" RC_PYTHON="$RC_PYTHON" SRC="$src" DST="$dst" python3 <<'PYEOF'
import os, re
src, dst = os.environ["SRC"], os.environ["DST"]
rc_repo, rc_python = os.environ["RC_REPO"], os.environ["RC_PYTHON"]
with open(src) as fh:
    text = fh.read()
text = text.replace("<RC_REPO>", rc_repo)
# Swap any `python3 <abs path>/src/hooks/...` style hook command for the
# venv interpreter. Conservative: only the bare leading `python3` token.
text = re.sub(r'(?m)(^|"\s*command":\s*")python3(\s)', r'\1' + rc_python + r'\2', text)
text = re.sub(r'(\["?)python3("?,)', r'\1' + rc_python + r'\2', text)
with open(dst, "w") as fh:
    fh.write(text)
PYEOF
}

# ---------------------------------------------------------------------------
# 1. direnv
# ---------------------------------------------------------------------------
_have() { command -v "$1" >/dev/null 2>&1; }
_root() { [[ "${EUID:-$(id -u)}" -eq 0 ]]; }
_sudo() { _have sudo && ! _root; }

ensure_direnv() {
  if _have direnv; then
    ok "direnv already installed ($(direnv version 2>/dev/null | head -1))"
    return
  fi
  warn "direnv missing — attempting install"
  if _have brew; then
    brew install direnv && ok "installed direnv via brew" && return
  fi
  if _have apt-get; then
    if _root;     then apt-get update -qq && apt-get install -y direnv && ok "installed direnv via apt"        && return
    elif _sudo;   then sudo apt-get update -qq && sudo apt-get install -y direnv && ok "installed direnv via sudo apt" && return
    fi
  fi
  if _have dnf; then
    if _root;   then dnf install -y direnv && ok "installed direnv via dnf"        && return
    elif _sudo; then sudo dnf install -y direnv && ok "installed direnv via sudo dnf" && return
    fi
  fi
  if _have pacman; then
    if _root;   then pacman -S --noconfirm direnv && ok "installed direnv via pacman"        && return
    elif _sudo; then sudo pacman -S --noconfirm direnv && ok "installed direnv via sudo pacman" && return
    fi
  fi
  warn "could not auto-install direnv. See https://direnv.net/docs/installation.html"
  warn "the script will continue; the generated .envrc just won't auto-load until direnv is on PATH"
}

# ---------------------------------------------------------------------------
# 2. .envrc (direnv)
# ---------------------------------------------------------------------------
install_envrc() {
  if [[ -e .envrc ]]; then
    skip ".envrc already exists — leaving it alone"
    return
  fi
  cat > .envrc <<EOF
# reasoning-core — repo-scoped activation. Loaded by direnv on \`cd\`.
# Generated by $RC_REPO/install.sh on $(date -u +%FT%TZ).

export RC_REPO="\${RC_REPO:-$RC_REPO}"

if [[ ! -f "\$RC_REPO/src/hooks/pre_edit_guard.py" ]]; then
  echo "[direnv] WARN: RC_REPO=\$RC_REPO is not a valid reasoning-core checkout"
fi

# Put the reasoning-core venv on PATH for this shell. The hook commands
# also reference \$RC_REPO/.venv/bin/python explicitly so they don't rely
# on this — but having the venv on PATH means ad-hoc \`python3 -c "import
# src.s2_core"\` works without activating the venv by hand.
if [[ -d "\$RC_REPO/.venv/bin" ]]; then
  PATH_add "\$RC_REPO/.venv/bin"
else
  echo "[direnv] WARN: \$RC_REPO/.venv missing — run 'python3 -m venv .venv && pip install -r requirements.txt' from \$RC_REPO"
fi

# Sidecar tuning. Override per-machine in .envrc.local (gitignored).
export S2_DEVICE="\${S2_DEVICE:-cpu}"
export S2_PORT="\${S2_PORT:-8765}"
export S2_TIMEOUT="\${S2_TIMEOUT:-30}"
export S2_FAIL_CLOSED="\${S2_FAIL_CLOSED:-0}"
export HF_HOME="\${HF_HOME:-\$HOME/.cache/huggingface}"

# Hook policy. Shadow mode ON by default — decisions are logged, not enforced.
# Flip RC_SHADOW_MODE=0 in .envrc.local once you've watched the audit log for
# a few sessions and trust the gate.
export RC_SHADOW_MODE="\${RC_SHADOW_MODE:-1}"
export RC_PLAN_BLOCK="\${RC_PLAN_BLOCK:-0}"

# Opt-in features (all default off):
#   RC_EMBEDDER         — embedder backend; default mamba-130m (130M, ~200MB).
#                         Alternatives: codestral-mamba (7B, code-pretrained,
#                         needs SHA pin via RC_MISTRALAI_MAMBA_CODESTRAL_7B_V0_1_REVISION),
#                         bge-code, unixcoder-base, random-mamba.
#   RC_RULE_ENGINE      — enable .reasoning-core/rules.yaml symbolic gate.
#                         Fail-closed by default; RC_RULE_ENGINE_LENIENT=1 to soft-degrade.
#   RC_PROJECT_INDEX    — fill project_fan_in / project_coupling risk dims by
#                         indexing the whole repo once per session.
#   RC_DIFF_AUDIT       — Stop-hook scans last assistant diff with validate_unified_diff.
# export RC_EMBEDDER=mamba-130m
# export RC_RULE_ENGINE=1
# export RC_PROJECT_INDEX=1
# export RC_DIFF_AUDIT=1

# Personal toggles / secrets → .envrc.local (gitignored, sourced last).
[[ -f .envrc.local ]] && source_env .envrc.local
EOF
  ok "wrote .envrc"
  record ".envrc"
}

# ---------------------------------------------------------------------------
# 3. .claude/settings.local.json
# ---------------------------------------------------------------------------
install_claude() {
  local target=".claude/settings.local.json"
  if [[ -e "$target" ]]; then
    skip "$target already exists — leaving it alone"
    return
  fi
  mkdir -p .claude
  # Note: the JSON is emitted with literal ${RC_REPO} / ${RC_PYTHON}
  # placeholders. We could pre-expand them, but Claude Code's hook runner
  # evaluates POSIX parameter expansion on the command string, so leaving
  # them in keeps the file portable across machines that share an
  # $HOME/.envrc.
  cat > "$target" <<'EOF'
{
  "_note": "reasoning-core hooks. ${RC_REPO} and ${RC_PYTHON} (=$RC_REPO/.venv/bin/python) resolve via .envrc so this file is portable across machines.",
  "hooks": {
    "PreToolUse": [
      { "matcher": "Write",
        "hooks": [{ "type": "command", "command": "${RC_PYTHON:-${RC_REPO}/.venv/bin/python} ${RC_REPO}/src/hooks/pre_plan_guard.py", "timeout": 15000 }] },
      { "matcher": "Edit|Write|MultiEdit",
        "hooks": [{ "type": "command", "command": "${RC_PYTHON:-${RC_REPO}/.venv/bin/python} ${RC_REPO}/src/hooks/pre_edit_guard.py", "timeout": 60000 }] },
      { "matcher": "Bash",
        "hooks": [{ "type": "command", "command": "${RC_PYTHON:-${RC_REPO}/.venv/bin/python} ${RC_REPO}/src/hooks/pre_bash_guard.py", "timeout": 5000 }] },
      { "matcher": "Task",
        "hooks": [{ "type": "command", "command": "${RC_PYTHON:-${RC_REPO}/.venv/bin/python} ${RC_REPO}/src/hooks/pre_task_guard.py", "timeout": 5000 }] }
    ],
    "PostToolUse": [
      { "matcher": "Bash",
        "hooks": [{ "type": "command", "command": "${RC_PYTHON:-${RC_REPO}/.venv/bin/python} ${RC_REPO}/src/hooks/post_bash_revive.py", "timeout": 5000 }] },
      { "matcher": "Edit|Write|MultiEdit",
        "hooks": [{ "type": "command", "command": "${RC_PYTHON:-${RC_REPO}/.venv/bin/python} ${RC_REPO}/src/hooks/post_batch_lang_audit.py", "timeout": 5000 }] }
    ],
    "SessionStart": [
      { "hooks": [
          { "type": "command", "command": "${RC_PYTHON:-${RC_REPO}/.venv/bin/python} ${RC_REPO}/src/hooks/session_start_manifest.py", "timeout": 30000 },
          { "type": "command", "command": "${RC_PYTHON:-${RC_REPO}/.venv/bin/python} ${RC_REPO}/src/hooks/session_resume_inject.py", "timeout": 5000 }
      ]}
    ],
    "UserPromptSubmit": [
      { "hooks": [{ "type": "command", "command": "${RC_PYTHON:-${RC_REPO}/.venv/bin/python} ${RC_REPO}/src/hooks/session_resume_inject.py", "timeout": 5000 }] }
    ],
    "PreCompact": [
      { "hooks": [{ "type": "command", "command": "${RC_PYTHON:-${RC_REPO}/.venv/bin/python} ${RC_REPO}/src/hooks/pre_compact_guard.py", "timeout": 5000 }] }
    ]
  },
  "mcpServers": {
    "hybrid-reasoner": {
      "type": "stdio",
      "command": "${RC_PYTHON:-${RC_REPO}/.venv/bin/python}",
      "args": ["-m", "src.mcp_reasoner"],
      "cwd": "${RC_REPO}"
    }
  }
}
EOF
  ok "wrote $target"
  record "$target"
}

# ---------------------------------------------------------------------------
# 4. .gemini/settings.json
# ---------------------------------------------------------------------------
install_gemini() {
  local target=".gemini/settings.json"
  local template="$RC_REPO/.gemini/settings.json.template"
  if [[ ! -f "$template" ]]; then
    warn "gemini template missing at $template — skipping"
    return
  fi
  if [[ -e "$target" ]]; then
    skip "$target already exists — leaving it alone"
    return
  fi
  mkdir -p .gemini
  render_template "$template" "$target"
  if ! python3 -c "import json,sys; json.load(open(sys.argv[1]))" "$target" 2>/dev/null; then
    fail "generated $target is not valid JSON"
    rm -f "$target"
    return
  fi
  ok "wrote $target"
  record "$target"

  if [[ -f "$RC_REPO/.gemini/skills/reasoning/SKILL.md" && ! -e .gemini/skills/reasoning/SKILL.md ]]; then
    mkdir -p .gemini/skills/reasoning
    cp "$RC_REPO/.gemini/skills/reasoning/SKILL.md" .gemini/skills/reasoning/SKILL.md
    ok "wrote .gemini/skills/reasoning/SKILL.md"
    record ".gemini/skills/reasoning/SKILL.md"
  fi
}

# ---------------------------------------------------------------------------
# 5. .copilot/* + global ~/.copilot/mcp-config.json
# ---------------------------------------------------------------------------
install_copilot() {
  if [[ ! -d "$RC_REPO/.copilot" ]]; then
    warn "copilot scaffold missing at $RC_REPO/.copilot — skipping"
    return
  fi
  mkdir -p .copilot/skills/reasoning
  if [[ ! -e .copilot/copilot-instructions.md ]]; then
    cp "$RC_REPO/.copilot/copilot-instructions.md" .copilot/copilot-instructions.md
    ok "wrote .copilot/copilot-instructions.md"
    record ".copilot/copilot-instructions.md"
  else
    skip ".copilot/copilot-instructions.md already exists"
  fi
  if [[ -f "$RC_REPO/.copilot/skills/reasoning/SKILL.md" && ! -e .copilot/skills/reasoning/SKILL.md ]]; then
    cp "$RC_REPO/.copilot/skills/reasoning/SKILL.md" .copilot/skills/reasoning/SKILL.md
    ok "wrote .copilot/skills/reasoning/SKILL.md"
    record ".copilot/skills/reasoning/SKILL.md"
  fi

  # Merge into ~/.copilot/mcp-config.json with file-lock + atomic rename.
  local target="$HOME/.copilot/mcp-config.json"
  mkdir -p "$HOME/.copilot"
  [[ -f "$target" ]] && cp "$target" "$target.bak.$(date +%s)"
  local lockfile="$target.lock"
  exec 9>"$lockfile"
  if command -v flock >/dev/null 2>&1; then
    flock -x 9
  fi
  TARGET="$target" RC_REPO="$RC_REPO" RC_PYTHON="$RC_PYTHON" python3 <<'PYEOF'
import json, os
target = os.environ["TARGET"]
rc_repo, rc_python = os.environ["RC_REPO"], os.environ["RC_PYTHON"]
data = {}
if os.path.exists(target):
    try:
        with open(target) as fh:
            data = json.load(fh)
    except Exception:
        data = {}
servers = data.setdefault("mcpServers", {})
servers["hybrid-reasoner"] = {
    "command": rc_python,
    "args": ["-m", "src.mcp_reasoner"],
    "cwd": rc_repo,
    "env": {},
}
tmp = target + ".tmp"
with open(tmp, "w") as fh:
    json.dump(data, fh, indent=2, sort_keys=True)
os.rename(tmp, target)
PYEOF
  # Release the flock before returning.
  exec 9>&-
  ok "merged hybrid-reasoner into $target"
}

# ---------------------------------------------------------------------------
# 6. .vibe/* + ~/.vibe/trusted_folders.toml entry
# ---------------------------------------------------------------------------
install_vibe() {
  local template="$RC_REPO/.vibe/config.toml.template"
  if [[ ! -f "$template" ]]; then
    warn "vibe template missing at $template — skipping"
    return
  fi
  mkdir -p .vibe/skills/reasoning
  local target=".vibe/config.toml"
  if [[ ! -e "$target" ]]; then
    render_template "$template" "$target"
    ok "wrote $target"
    record "$target"
  else
    skip "$target already exists"
  fi
  if [[ -f "$RC_REPO/.vibe/AGENTS.md" && ! -e .vibe/AGENTS.md ]]; then
    cp "$RC_REPO/.vibe/AGENTS.md" .vibe/AGENTS.md
    ok "wrote .vibe/AGENTS.md"
    record ".vibe/AGENTS.md"
  fi
  if [[ -f "$RC_REPO/.vibe/skills/reasoning/SKILL.md" && ! -e .vibe/skills/reasoning/SKILL.md ]]; then
    cp "$RC_REPO/.vibe/skills/reasoning/SKILL.md" .vibe/skills/reasoning/SKILL.md
    ok "wrote .vibe/skills/reasoning/SKILL.md"
    record ".vibe/skills/reasoning/SKILL.md"
  fi

  # Trusted-folder registration with proper TOML quoting. printf %q emits
  # shell escapes (not TOML), which can produce an unparseable file for
  # paths containing single quotes, backslashes, or other specials.
  local trusted="$HOME/.vibe/trusted_folders.toml"
  mkdir -p "$HOME/.vibe"
  TRUSTED="$trusted" HERE="$TARGET_REPO" python3 <<'PYEOF'
import os, re
trusted, here = os.environ["TRUSTED"], os.environ["HERE"]
# TOML basic-string escapes: \ " and control chars. Path strings in
# practice contain none of those, but encode defensively.
def toml_quote(s: str) -> str:
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'
quoted = toml_quote(here)
new_block = f"\n[[trusted]]\npath = {quoted}\n"
existing = ""
if os.path.exists(trusted):
    with open(trusted) as fh:
        existing = fh.read()
# Exact-match the path line under a [[trusted]] header — defend against
# false positives on /foo/bar vs /foo/bar-baz.
pattern = re.compile(
    r'\[\[trusted\]\]\s*\npath\s*=\s*' + re.escape(quoted) + r'\s*(?:\n|$)',
    re.MULTILINE,
)
if pattern.search(existing):
    print(f"  \033[33m·\033[0m {here} already trusted in {trusted}")
else:
    with open(trusted, "a") as fh:
        fh.write(new_block)
    print(f"  \033[32m✓\033[0m added {here} to {trusted}")
PYEOF
}

# ---------------------------------------------------------------------------
# 7. .gitignore
# ---------------------------------------------------------------------------
update_gitignore() {
  local created=0
  if [[ ! -f .gitignore ]]; then
    warn ".gitignore missing — creating one so reasoning-core's generated files don't accidentally get committed"
    : > .gitignore
    created=1
  fi
  if grep -qxF '# >>> reasoning-core >>>' .gitignore; then
    skip ".gitignore already has reasoning-core block"
    return
  fi
  cat >> .gitignore <<'EOF'

# >>> reasoning-core >>>
.envrc.local
.claude/settings.local.json
.gemini/settings.json
.vibe/config.toml
.reasoning-core/
# <<< reasoning-core <<<
EOF
  if [[ "$created" -eq 1 ]]; then
    ok "created .gitignore with reasoning-core block"
    record ".gitignore"   # we created it — uninstall removes it
  else
    ok "updated .gitignore"
  fi
}

# ---------------------------------------------------------------------------
# 8. direnv allow
# ---------------------------------------------------------------------------
direnv_allow() {
  if command -v direnv >/dev/null 2>&1 && [[ -f .envrc ]]; then
    direnv allow . 2>/dev/null && ok "direnv allow .  (env active in this directory)"
  fi
}

# ---------------------------------------------------------------------------
# Run
# ---------------------------------------------------------------------------
printf '\nreasoning-core install\n'
printf '  RC_REPO     = %s\n' "$RC_REPO"
printf '  TARGET_REPO = %s\n\n' "$TARGET_REPO"

if [[ ! -x "$RC_PYTHON" ]]; then
  warn "no venv at $RC_PYTHON yet — finish step 'Next' below before launching claude/gemini/copilot/vibe"
fi

ensure_direnv
install_envrc
install_claude
install_gemini
install_copilot
install_vibe
update_gitignore
direnv_allow

cat <<EOF

done. manifest: $MANIFEST

next (one-time bootstrap of the framework itself):
  cd "$RC_REPO" && python3 -m venv .venv && source .venv/bin/activate
  pip install -r requirements.txt
  huggingface-cli download state-spaces/mamba-130m-hf
  bash scripts/start-sidecar.sh       # or scripts/install-supervisor-launchagent.sh on macOS

then, from this repo ($TARGET_REPO):
  claude                              # hooks now active

to revert:  cd "$TARGET_REPO" && bash "$RC_REPO/uninstall.sh"
EOF
