#!/usr/bin/env bash
# reasoning-core — one-command install.
#
# Run this from the repo you want to gate. The script auto-detects
# $RC_REPO from its own location and writes per-repo config for every
# supported AI coding CLI (Claude Code, Gemini CLI, GitHub Copilot CLI,
# Mistral Vibe CLI) plus a direnv `.envrc`.
#
# Idempotent: files that already exist are skipped (the script will tell
# you which ones). A manifest of created paths is written to
# `.reasoning-core/install.manifest` so `uninstall.sh` knows what to remove.
#
# Defaults are conservative (shadow mode ON, fail-open). Promote later by
# editing `.envrc.local` per `docs/USAGE.md`.

set -euo pipefail

RC_REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TARGET_REPO="$(pwd)"
MANIFEST_DIR=".reasoning-core"
MANIFEST="$MANIFEST_DIR/install.manifest"

ok()    { printf '  \033[32m✓\033[0m %s\n' "$*"; }
skip()  { printf '  \033[33m·\033[0m %s\n' "$*"; }
warn()  { printf '  \033[33m!\033[0m %s\n' "$*" >&2; }
fail()  { printf '  \033[31m✗\033[0m %s\n' "$*" >&2; }

if [[ ! -d "$RC_REPO/src/hooks" ]]; then
  fail "RC_REPO=$RC_REPO is not a valid reasoning-core checkout (no src/hooks/)"
  exit 2
fi

if [[ ! -d .git ]] && [[ ! -f .git ]]; then
  warn "$TARGET_REPO is not a git repo. Continuing anyway."
fi

mkdir -p "$MANIFEST_DIR"
: > "$MANIFEST"
record() { printf '%s\n' "$1" >> "$MANIFEST"; }

# ---------------------------------------------------------------------------
# 1. direnv
# ---------------------------------------------------------------------------
ensure_direnv() {
  if command -v direnv >/dev/null 2>&1; then
    ok "direnv already installed ($(direnv version 2>/dev/null | head -1))"
    return
  fi
  warn "direnv missing — attempting install"
  if command -v brew >/dev/null 2>&1; then
    brew install direnv && ok "installed direnv via brew" && return
  fi
  if command -v apt-get >/dev/null 2>&1 && [[ "${EUID:-$(id -u)}" -eq 0 || -n "${SUDO_USER:-}" ]]; then
    apt-get update -qq && apt-get install -y direnv && ok "installed direnv via apt" && return
  fi
  if command -v sudo >/dev/null 2>&1 && command -v apt-get >/dev/null 2>&1; then
    sudo apt-get update -qq && sudo apt-get install -y direnv && ok "installed direnv via sudo apt" && return
  fi
  if command -v dnf >/dev/null 2>&1; then
    sudo dnf install -y direnv && ok "installed direnv via dnf" && return
  fi
  if command -v pacman >/dev/null 2>&1; then
    sudo pacman -S --noconfirm direnv && ok "installed direnv via pacman" && return
  fi
  warn "could not auto-install direnv. See https://direnv.net/docs/installation.html"
  warn "the script will continue; the generated .envrc just won't auto-load until direnv is on PATH"
}

# ---------------------------------------------------------------------------
# 2. .envrc (direnv)
# ---------------------------------------------------------------------------
install_envrc() {
  if [[ -e .envrc ]]; then
    skip ".envrc already exists — leaving it alone"
    return
  fi
  cat > .envrc <<EOF
# reasoning-core — repo-scoped activation. Loaded by direnv on \`cd\`.
# Generated by $RC_REPO/install.sh on $(date -u +%FT%TZ).

export RC_REPO="\${RC_REPO:-$RC_REPO}"

if [[ ! -f "\$RC_REPO/src/hooks/pre_edit_guard.py" ]]; then
  echo "[direnv] WARN: RC_REPO=\$RC_REPO is not a valid reasoning-core checkout"
fi

# Sidecar tuning. Override per-machine in .envrc.local (gitignored).
export S2_DEVICE="\${S2_DEVICE:-cpu}"
export S2_PORT="\${S2_PORT:-8765}"
export S2_FAIL_CLOSED="\${S2_FAIL_CLOSED:-0}"
export HF_HOME="\${HF_HOME:-\$HOME/.cache/huggingface}"

# Hook policy. Shadow mode ON by default — decisions are logged, not enforced.
# Flip RC_SHADOW_MODE=0 in .envrc.local once you've watched the audit log for
# a few sessions and trust the gate.
export RC_SHADOW_MODE="\${RC_SHADOW_MODE:-1}"
export RC_PLAN_BLOCK="\${RC_PLAN_BLOCK:-0}"

# Personal toggles / secrets → .envrc.local (gitignored, sourced last).
[[ -f .envrc.local ]] && source_env .envrc.local
EOF
  ok "wrote .envrc"
  record ".envrc"
}

# ---------------------------------------------------------------------------
# 3. .claude/settings.local.json
# ---------------------------------------------------------------------------
install_claude() {
  local target=".claude/settings.local.json"
  if [[ -e "$target" ]]; then
    skip "$target already exists — leaving it alone"
    return
  fi
  mkdir -p .claude
  cat > "$target" <<'EOF'
{
  "_note": "reasoning-core hooks. Hook commands resolve via $RC_REPO so this file is portable across machines.",
  "hooks": {
    "PreToolUse": [
      { "matcher": "Write",
        "hooks": [{ "type": "command", "command": "python3 ${RC_REPO}/src/hooks/pre_plan_guard.py", "timeout": 15000 }] },
      { "matcher": "Edit|Write|MultiEdit",
        "hooks": [{ "type": "command", "command": "python3 ${RC_REPO}/src/hooks/pre_edit_guard.py", "timeout": 60000 }] },
      { "matcher": "Bash",
        "hooks": [{ "type": "command", "command": "python3 ${RC_REPO}/src/hooks/pre_bash_guard.py", "timeout": 5000 }] },
      { "matcher": "Task",
        "hooks": [{ "type": "command", "command": "python3 ${RC_REPO}/src/hooks/pre_task_guard.py", "timeout": 5000 }] }
    ],
    "PostToolUse": [
      { "matcher": "Bash",
        "hooks": [{ "type": "command", "command": "python3 ${RC_REPO}/src/hooks/post_bash_revive.py", "timeout": 5000 }] },
      { "matcher": "Edit|Write|MultiEdit",
        "hooks": [{ "type": "command", "command": "python3 ${RC_REPO}/src/hooks/post_batch_lang_audit.py", "timeout": 5000 }] }
    ],
    "SessionStart": [
      { "hooks": [
          { "type": "command", "command": "python3 ${RC_REPO}/src/hooks/session_start_manifest.py", "timeout": 30000 },
          { "type": "command", "command": "python3 ${RC_REPO}/src/hooks/session_resume_inject.py", "timeout": 5000 }
      ]}
    ],
    "UserPromptSubmit": [
      { "hooks": [{ "type": "command", "command": "python3 ${RC_REPO}/src/hooks/session_resume_inject.py", "timeout": 5000 }] }
    ],
    "PreCompact": [
      { "hooks": [{ "type": "command", "command": "python3 ${RC_REPO}/src/hooks/pre_compact_guard.py", "timeout": 5000 }] }
    ]
  },
  "mcpServers": {
    "hybrid-reasoner": {
      "type": "stdio",
      "command": "python3",
      "args": ["-m", "src.mcp_reasoner"],
      "cwd": "${RC_REPO}"
    }
  }
}
EOF
  ok "wrote $target"
  record "$target"
}

# ---------------------------------------------------------------------------
# 4. .gemini/settings.json
# ---------------------------------------------------------------------------
install_gemini() {
  local target=".gemini/settings.json"
  local template="$RC_REPO/.gemini/settings.json.template"
  if [[ ! -f "$template" ]]; then
    warn "gemini template missing at $template — skipping"
    return
  fi
  if [[ -e "$target" ]]; then
    skip "$target already exists — leaving it alone"
    return
  fi
  mkdir -p .gemini
  sed "s|<RC_REPO>|$RC_REPO|g" "$template" > "$target"
  if ! python3 -c "import json,sys; json.load(open('$target'))" 2>/dev/null; then
    fail "generated $target is not valid JSON"
    rm -f "$target"
    return
  fi
  ok "wrote $target"
  record "$target"

  if [[ -f "$RC_REPO/.gemini/skills/reasoning/SKILL.md" && ! -e .gemini/skills/reasoning/SKILL.md ]]; then
    mkdir -p .gemini/skills/reasoning
    cp "$RC_REPO/.gemini/skills/reasoning/SKILL.md" .gemini/skills/reasoning/SKILL.md
    ok "wrote .gemini/skills/reasoning/SKILL.md"
    record ".gemini/skills/reasoning/SKILL.md"
  fi
}

# ---------------------------------------------------------------------------
# 5. .copilot/* + global ~/.copilot/mcp-config.json
# ---------------------------------------------------------------------------
install_copilot() {
  if [[ ! -d "$RC_REPO/.copilot" ]]; then
    warn "copilot scaffold missing at $RC_REPO/.copilot — skipping"
    return
  fi
  mkdir -p .copilot/skills/reasoning
  if [[ ! -e .copilot/copilot-instructions.md ]]; then
    cp "$RC_REPO/.copilot/copilot-instructions.md" .copilot/copilot-instructions.md
    ok "wrote .copilot/copilot-instructions.md"
    record ".copilot/copilot-instructions.md"
  else
    skip ".copilot/copilot-instructions.md already exists"
  fi
  if [[ -f "$RC_REPO/.copilot/skills/reasoning/SKILL.md" && ! -e .copilot/skills/reasoning/SKILL.md ]]; then
    cp "$RC_REPO/.copilot/skills/reasoning/SKILL.md" .copilot/skills/reasoning/SKILL.md
    ok "wrote .copilot/skills/reasoning/SKILL.md"
    record ".copilot/skills/reasoning/SKILL.md"
  fi

  # Merge into ~/.copilot/mcp-config.json with file-lock + atomic rename.
  local target="$HOME/.copilot/mcp-config.json"
  mkdir -p "$HOME/.copilot"
  [[ -f "$target" ]] && cp "$target" "$target.bak.$(date +%s)"
  local lockfile="$target.lock"
  exec 9>"$lockfile"
  if command -v flock >/dev/null 2>&1; then
    flock -x 9
  fi
  python3 - "$target" "$RC_REPO" <<'PYEOF'
import json, os, sys
target, rc_repo = sys.argv[1], sys.argv[2]
data = {}
if os.path.exists(target):
    try:
        data = json.load(open(target))
    except Exception:
        data = {}
servers = data.setdefault("mcpServers", {})
servers["hybrid-reasoner"] = {
    "command": "python3",
    "args": ["-m", "src.mcp_reasoner"],
    "cwd": rc_repo,
    "env": {},
}
tmp = target + ".tmp"
with open(tmp, "w") as fh:
    json.dump(data, fh, indent=2, sort_keys=True)
os.rename(tmp, target)
PYEOF
  ok "merged hybrid-reasoner into $target"
}

# ---------------------------------------------------------------------------
# 6. .vibe/* + ~/.vibe/trusted_folders.toml entry
# ---------------------------------------------------------------------------
install_vibe() {
  local template="$RC_REPO/.vibe/config.toml.template"
  if [[ ! -f "$template" ]]; then
    warn "vibe template missing at $template — skipping"
    return
  fi
  mkdir -p .vibe/skills/reasoning
  local target=".vibe/config.toml"
  if [[ ! -e "$target" ]]; then
    sed "s|<RC_REPO>|$RC_REPO|g" "$template" > "$target"
    ok "wrote $target"
    record "$target"
  else
    skip "$target already exists"
  fi
  if [[ -f "$RC_REPO/.vibe/AGENTS.md" && ! -e .vibe/AGENTS.md ]]; then
    cp "$RC_REPO/.vibe/AGENTS.md" .vibe/AGENTS.md
    ok "wrote .vibe/AGENTS.md"
    record ".vibe/AGENTS.md"
  fi
  if [[ -f "$RC_REPO/.vibe/skills/reasoning/SKILL.md" && ! -e .vibe/skills/reasoning/SKILL.md ]]; then
    cp "$RC_REPO/.vibe/skills/reasoning/SKILL.md" .vibe/skills/reasoning/SKILL.md
    ok "wrote .vibe/skills/reasoning/SKILL.md"
    record ".vibe/skills/reasoning/SKILL.md"
  fi

  # Trusted-folder registration (exact-line match — don't false-positive on /foo/bar-baz)
  local trusted="$HOME/.vibe/trusted_folders.toml"
  mkdir -p "$HOME/.vibe"
  local pwd_line
  pwd_line=$(printf 'path = %q' "$TARGET_REPO")
  if ! grep -qxF "$pwd_line" "$trusted" 2>/dev/null; then
    printf '\n[[trusted]]\npath = %q\n' "$TARGET_REPO" >> "$trusted"
    ok "added $TARGET_REPO to $trusted"
  fi
}

# ---------------------------------------------------------------------------
# 7. .gitignore
# ---------------------------------------------------------------------------
update_gitignore() {
  [[ ! -f .gitignore ]] && return
  if grep -qxF '# >>> reasoning-core >>>' .gitignore; then
    skip ".gitignore already has reasoning-core block"
    return
  fi
  cat >> .gitignore <<'EOF'

# >>> reasoning-core >>>
.envrc.local
.claude/settings.local.json
.gemini/settings.json
.vibe/config.toml
.reasoning-core/
# <<< reasoning-core <<<
EOF
  ok "updated .gitignore"
}

# ---------------------------------------------------------------------------
# 8. direnv allow
# ---------------------------------------------------------------------------
direnv_allow() {
  if command -v direnv >/dev/null 2>&1 && [[ -f .envrc ]]; then
    direnv allow . 2>/dev/null && ok "direnv allow .  (env active in this directory)"
  fi
}

# ---------------------------------------------------------------------------
# Run
# ---------------------------------------------------------------------------
printf '\nreasoning-core install\n'
printf '  RC_REPO     = %s\n' "$RC_REPO"
printf '  TARGET_REPO = %s\n\n' "$TARGET_REPO"

ensure_direnv
install_envrc
install_claude
install_gemini
install_copilot
install_vibe
update_gitignore
direnv_allow

cat <<EOF

done. manifest: $MANIFEST

next:
  cd "$RC_REPO" && python3 -m venv .venv && source .venv/bin/activate
  pip install -r requirements.txt
  huggingface-cli download state-spaces/mamba-130m-hf
  bash scripts/start-sidecar.sh       # or scripts/install-supervisor-launchagent.sh on macOS
  cd "$TARGET_REPO" && claude         # hooks now active

to revert:  bash "$RC_REPO/uninstall.sh"
EOF
