#!/usr/bin/env bash
# Quick-enable reasoning-core for the CURRENT repo.
#
# Drops two files into the cwd:
#   .envrc                       — sets RC_REPO + opt-in iter-3 levers
#   .claude/settings.local.json  — registers all reasoning-core hooks
#
# Idempotent: refuses to overwrite either file if it already exists.
# Repo-scoped: nothing is written outside the cwd.
#
# Usage (from inside the repo you want to gate):
#   RC_REPO=/path/to/reasoning-core bash $RC_REPO/scripts/enable-in-repo.sh
set -euo pipefail

if [[ -z "${RC_REPO:-}" ]]; then
  echo "error: RC_REPO is unset. Export it to the path of your reasoning-core clone:"
  echo "  export RC_REPO=\$HOME/Repos/personal/reasoning-core"
  exit 2
fi
if [[ ! -d "$RC_REPO/src/hooks" ]]; then
  echo "error: RC_REPO=$RC_REPO does not contain src/hooks/ — wrong path?"
  exit 2
fi
if [[ ! -d .git ]] && [[ ! -f .git ]]; then
  echo "warn: $(pwd) is not a git repo. Continuing anyway."
fi

target_envrc=".envrc"
target_settings=".claude/settings.local.json"

if [[ -e "$target_envrc" ]] || [[ -e "$target_settings" ]]; then
  echo "error: refusing to overwrite existing files:"
  [[ -e "$target_envrc" ]] && echo "  $target_envrc"
  [[ -e "$target_settings" ]] && echo "  $target_settings"
  echo "remove them first, or merge by hand against the heredoc blocks in $RC_REPO/scripts/enable-in-repo.sh."
  exit 1
fi

mkdir -p .claude

cat > "$target_envrc" <<EOF
# reasoning-core — repo-scoped activation. Loaded by direnv on \`cd\`.
# Generated by $RC_REPO/scripts/enable-in-repo.sh.

export RC_REPO="\${RC_REPO:-$RC_REPO}"

# Sanity: warn loudly if RC_REPO points somewhere stale.
if [[ ! -f "\$RC_REPO/src/hooks/pre_edit_guard.py" ]]; then
  echo "[direnv] WARN: RC_REPO=\$RC_REPO is not a valid reasoning-core checkout"
fi

# Sidecar tuning. Override per-machine in .envrc.local (gitignored).
export S2_DEVICE="\${S2_DEVICE:-cpu}"
export S2_PORT="\${S2_PORT:-8765}"
export S2_FAIL_CLOSED=1
export HF_HOME="\${HF_HOME:-\$HOME/.cache/huggingface}"

# Hook policy: enforce decisions (set to 0 for shadow/observation mode).
export RC_PLAN_BLOCK=1
export RC_SHADOW_MODE=0

# Iter-3 levers — opt in here per repo. Both default OFF.
# RC_BEST_EFFORT_SPEC=1: SessionStart overlay nudging the agent away
#   from "DIVERGENCES.md alone" gameability on missing-infra tasks.
# RC_PLAN_GROUNDING=1: warn when the agent edits a file not in PLAN.md.
#   =2 escalates to hard block.
# export RC_BEST_EFFORT_SPEC=1
# export RC_PLAN_GROUNDING=1

# Personal toggles / secrets → .envrc.local (gitignored).
[[ -f .envrc.local ]] && source_env .envrc.local
EOF

cat > "$target_settings" <<'EOF'
{
  "_note": "reasoning-core hooks. Hook commands resolve via $RC_REPO so this file is portable across machines.",
  "hooks": {
    "PreToolUse": [
      {
        "matcher": "Write",
        "hooks": [
          { "type": "command", "command": "python3 ${RC_REPO}/src/hooks/pre_plan_guard.py", "timeout": 15000 }
        ]
      },
      {
        "matcher": "Edit|Write|MultiEdit",
        "hooks": [
          { "type": "command", "command": "python3 ${RC_REPO}/src/hooks/pre_edit_guard.py", "timeout": 60000 }
        ]
      },
      {
        "matcher": "Bash",
        "hooks": [
          { "type": "command", "command": "python3 ${RC_REPO}/src/hooks/pre_bash_guard.py" }
        ]
      },
      {
        "matcher": "Task",
        "hooks": [
          { "type": "command", "command": "python3 ${RC_REPO}/src/hooks/pre_task_guard.py" }
        ]
      }
    ],
    "PostToolUse": [
      {
        "matcher": "Bash",
        "hooks": [
          { "type": "command", "command": "python3 ${RC_REPO}/src/hooks/post_bash_revive.py" }
        ]
      },
      {
        "matcher": "Edit|Write|MultiEdit",
        "hooks": [
          { "type": "command", "command": "python3 ${RC_REPO}/src/hooks/post_batch_lang_audit.py", "timeout": 5000 }
        ]
      }
    ],
    "SessionStart": [
      {
        "hooks": [
          { "type": "command", "command": "python3 ${RC_REPO}/src/hooks/session_start_manifest.py", "timeout": 30000 },
          { "type": "command", "command": "python3 ${RC_REPO}/src/hooks/session_resume_inject.py", "timeout": 5000 },
          { "type": "command", "command": "python3 ${RC_REPO}/src/hooks/session_start_best_effort.py", "timeout": 10000 }
        ]
      }
    ],
    "UserPromptSubmit": [
      {
        "hooks": [
          { "type": "command", "command": "python3 ${RC_REPO}/src/hooks/session_resume_inject.py", "timeout": 5000 }
        ]
      }
    ],
    "PreCompact": [
      {
        "hooks": [
          { "type": "command", "command": "python3 ${RC_REPO}/src/hooks/pre_compact_guard.py", "timeout": 5000 }
        ]
      }
    ]
  },
  "mcpServers": {
    "hybrid-reasoner": {
      "type": "stdio",
      "command": "python3",
      "args": ["-m", "src.mcp_reasoner"],
      "cwd": "${RC_REPO}"
    }
  }
}
EOF

# Append to .gitignore if it exists and entries are missing.
if [[ -f .gitignore ]]; then
  grep -qxF '.envrc.local' .gitignore || echo '.envrc.local' >> .gitignore
  grep -qxF '.claude/settings.local.json' .gitignore || echo '.claude/settings.local.json' >> .gitignore
fi

cat <<EOF
wrote $target_envrc
wrote $target_settings

next:
  direnv allow .                          # load .envrc into this shell
  curl -fsS http://127.0.0.1:8765/health  # confirm sidecar is up (start it from \$RC_REPO if not)
  claude                                  # hooks fire on this session

opt-in iter-3 levers by uncommenting the two RC_BEST_EFFORT_SPEC / RC_PLAN_GROUNDING lines in $target_envrc, then \`direnv reload\`.
EOF
